266912: DI 86: MapAttribute support for entity mapkey https://bugs.eclipse.org/bugs/attachment.cgi?id=151667&action=diff http://wiki.eclipse.org/EclipseLink/Development/JPA_2.0/metamodel_api#DI_86:_20090921:_Handle_Embeddable_Type_keyType_in_MapAttributeImpl_constructor >Test model changes @Entity(name="ManufacturerMetamodel") public class Manufacturer extends Corporation implements java.io.Serializable{ ...     // UC9: no targetEntity, no MapKey, but generics are set (MapKey has an IdClass with an Embeddable)     @OneToMany(cascade=CascadeType.ALL, mappedBy="mappedManufacturerUC9") ---> new    private Map<Board, Enclosure> enclosureByBoardMapUC9; }
@Entity(name="EnclosureMetamodel")
@IdClass(org.eclipse.persistence.testing.models.jpa.metamodel.EnclosureIdClassPK.class)
public class Enclosure implements java.io.Serializable {
...    
    @Id    @Column(name="TYPE")
    public String type;
    @Id    @Column(name="LENGTH")
    protected String length;
    @Id    @Column(name="WIDTH")
    private String width;
 
    // The M:1 side is the owning side
    @Id    @ManyToOne
    @JoinColumn(name="PERSON_ID")
---> new    private Manufacturer mappedManufacturerUC9;
}
 
public class EnclosureIdClassPK {
...
    public String type;
    protected String length;
    private String width;
---> new    private Integer mappedManufacturerUC9;
}

>Testing before change
The following test passes with the change submitted in the DI86 patch below (without this fix we get the following test failure with the new model change above) 

TEST SUITE NAME: org.eclipse.persistence.testing.tests.jpa.metamodel.MetamodelMetamodelTest
TEST NAME: testMapAttribute_getKeyJavaType_UC9_DI86_Embeddable_IdClass_keyType_Method(org.eclipse.persistence.testing.tests.jpa.metamodel.MetamodelMetamodelTest)
##FAILURE##
RESULT:      Error (failure)
junit.framework.AssertionFailedError: expected:<class org.eclipse.persistence.testing.models.jpa.metamodel.Board> but was:<class java.lang.Integer>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:277)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at org.eclipse.persistence.testing.tests.jpa.metamodel.MetamodelMetamodelTest.testMapAttribute_getKeyJavaType_UC9_DI86_Embeddable_IdClass_keyType_Method(MetamodelMetamodelTest.java:4502)

>JPA LRG: 0,0
TEST MODEL NAME: (JUnit test): Metamodel
Errors: (failures): 0
Fatal Errors: (errors): 0
Passed: 120
Total Tests: 120

TEST MODEL NAME: (JUnit test): Criteria
Errors: (failures): 0
Fatal Errors: (errors): 0
Passed: 134
Total Tests: 134



Former-commit-id: ffd5125fbb27f41c2e948c8b27d701088ecc847a