Reverted fix for bug 302452 - JAXBContextFactory createContext methods should return org.eclipse.persistence.jaxb.JAXBContext
Reverted fix as it caused the following exception:

org.eclipse.persistence.jaxb.JAXBContextFactory.createContext([Lorg/eclipse/persistence/jaxb/TypeMappingInfo;Ljava/util/Map;Ljava/lang/ClassLoader;)Ljavax/xml/bind/JAXBContext;
java.lang.NoSuchMethodError:
org.eclipse.persistence.jaxb.JAXBContextFactory.createContext([Lorg/eclipse/persistence/jaxb/TypeMappingInfo;Ljava/util/Map;Ljava/lang/ClassLoader;)Ljavax/xml/bind/JAXBContext;


Former-commit-id: 91bdb787495d321b01274ee9396b4547a31fb200